### ISSUE TITLE
Multiple image pack locations

### ISSUE THREAD

**Issue by UseAfterFree-177** [h1262216/crazys-wm-mod#18]
I think it would be useful to allow for more than one directory for image packs.
1. An image pack can then be added/updated/removed as one unit. Today you can't do that without manually keeping track of the files.
2. An image pack can be installed without touching our install directory. (We would also need to move `config.xml` to the user's file area (`~/.WM/config.xml` in Linux; `%appdata%\WM\config.xml` on Windows.)
3. Name collisions can be handled in a more intelligent manner than "last one wins".

To begin with I'd use the same syntax as for the native `PATH` environment variable; as in
```
   ~/.WM/girls;~hhef/more-girls;$WM_STOCK_IMAGES
```

Future improvements could include:
* Zip-files as image packs (`path/to/girl-pack.zip`).
* All image packs in a named directory (`path/to/collection/*`), or in a named directory tree (`path/to/collection/**`).
With both these features in place, a user would be able to install an image pack just by copying it into the right directory (no need to unzip it first).

One more important thing: I don't think that any image pack should have any influence over any other pack -- instead the pack's curator should work with a copy of the "victim" pack.

**Comment by h1262216** [comment]
recursive scanning of a single directory tree should actually work already in the current version. For a quick workaround, placing a symlink to wherever you want to keep your packs should work, though I admittedly have not tested this.

I'm still in favour of allowing multiple locations, and your syntax looks fine, especially since we now have ~ replacement. Should this be game specific, though? You might have one playthrough with real images and one with drawings, for example.

**Comment by UseAfterFree-177** [comment]
More precisely, for Windows I'll use ';' for separator, like `%PATH%`. For Unix (Linux + Mac) I'll use ':', like `$PATH`.
I might be helpful and allow ';' in Unix; but I cannot allow ':' on Windows, because `C:\`.

I think that I can use the macro `__WINDOWS__` to see of I'm on Windows or not. Could you please check that on your compiler?

**Comment by h1262216** [comment]
we are defining (from cmake) the macro `UNIX`, which should do what you want, right?
maybe we should use ';' consistently, though.

**Comment by UseAfterFree-177** [comment]
';' would be consistent at our end, but not at the user's -- all other Unix progs would accept ':' here.

We already have a split here on '/' vs '\\', so this would just be the same thing once more. So, if I skip the helpfulness, we get `some/path:other/path` on Unix and `some\path;other\path` on Windows.

(Trivia: Many win32 syscalls are perfectly fine with '/' in paths; however, many helper functions _know_ that you can't do that, so they error out if you try.)

**Comment by UseAfterFree-177** [comment]
I think that `UNIX` is a CMake variable, not a `#define` -- unless we make it one ourselves.

Going by this overview (<https://caiorss.github.io/C-Cpp-Notes/Preprocessor_and_Macros.html>) `__unix__` or `_WIN32` would be what I need. I've verified both macros over here, so if you could do the same at your end, I'd feel safe using them.

**Comment by h1262216** [comment]
sorry, you're right, the CMake variable is `UNIX` and we use it to set a define `LINUX`.
```
if (UNIX)
    target_compile_definitions(WmGameObjects PUBLIC LINUX=1)
endif(UNIX)
```

Long term, I'm hoping to get rid of the file path representation split by switching to c++17 and std::filesystem.
I still think I'm in favour of keeping things consistent within our program. In the documentation (if we had one :) , we could just say that you specify a ; separated list of paths, instead of a system specific format.

If we ever add another config variable which may be set to a list of things (which are not search paths), I think ';' would end up being the reasonable choice. So the only strong argument for keeping it consistent with $PATH would be if we plan on supporting to get this from an environment variable. But for reading from the config xml, I think using ';' consistently is the better choice, though I guess it would be OK if on linux we also split on ':'.

**Comment by UseAfterFree-177** [comment]
That's what makes the quest for consistency so fun.

I'll go with just `;` on Windows, and both `;` and `:` elsewhere. Then we can document it as either "Native separator on all platforms" or "`;` on all platforms".

(And here's to C++17! :beers: )

**Comment by UseAfterFree-177** [comment]
And stuffing Mac into the Linux bin will work -- until suddenly one day it won't.
