### ISSUE TITLE
Character images keep repeating

### ISSUE THREAD

**Issue by TheChosen90** [h1262216/crazys-wm-mod#43]
Hello! First of all, thank you for continuing the work and keeping this project alive.

Now, there seems to be an issue with the new image system in that its not randomising properly. Clicking on the character is not giving a new image. Same when viewing a characters profile it seems to stick with one image. Same with characters available on the slave market. Its not a huge issue, but it also affects the weekly report, where the image of characters actions are repeated for the next reports, no matter what the action was or even if you change the characters job. I've occasionally seen it sort of "reset" and finally change an image and I feel like its somehow related to characters getting "GOODNEWS" in their weekly report (like when they level up, get a new trait or when they serve a customer for a first time). This issue doesn't exist when directly interacting with charcaters; that seems to randomize properly.

This issue exists in both of the latest versions. I've tried fooling around with the image tagger, but from my understanding the old images should still randomize properly even without having to tag them all properly for the new system. If that is the case, I would appreciate some proper documentation on how to use the tagger program (and even if it isn't, instructions on how to use it would still be welcome).

**Comment by h1262216** [comment]
Hi, thanks for the report. 
You are correct that the randomization of images should not depend on whether old or new tagging is used. 

Now, to address the actual issue, the answer has multiple parts:
1) Profile images (and similar) are only re-randomized every week, so if you select a girl again in the market or management screen, the same image is supposed to pop up until you advance the game by a week.
2) Images used for the end-of-week messages are also fixed for each event. More precisely, they are selected lazily (meaning not during job processing, but only if you actually click on it, to make "Next Week" faster) and cached (meaning that if you click on the same event twice, you will get the same message). So this is also deliberate. 
3) **However**, there is an error in the current image caching, that would reuse the same image even if the event changed. This is already fixed in the development version. 

I probably should release a new version soon, because this is a pretty significant bug.

**Comment by h1262216** [comment]
I've uploaded a new version, could you check if things are improved?

**Comment by TheChosen90** [comment]
Yes, I've played couple of hours and it seems to be working properly now. Thank you.
